### ISSUE TITLE
4.4 Compatibility

### ISSUE THREAD

**Issue by drodda** [eladnava/sunriser-android#3]
Is it possible to make it compatible with 4.4 KitKat?
I have compiled the app with minSdkVersion 19 and get no errors, but when launching it on a 4.4 device it closes immediately.

**Comment by drodda** [comment]
It appears to be caused by android.app.AlarmManager.getNextAlarmClock was added in api 21

**Comment by drodda** [comment]
I think I have a backwards-compatible solution that uses NEXT_ALARM_FORMATTED for <21 devices. I will test over the next few days of alarms.

**Comment by eladnava** [comment]
Hi @drodda,
That's correct! The `getNextAlarmClock()` method is the reason for the lack of compatibility with < API 21. Good catch!

However, do note that `NEXT_ALARM_FORMATTED` doesn't always return any (or at least, a valid) date representation of the phone's next scheduled alarm. So be sure not to assume that it always exists, or that its format is as expected.

I think that to add compatibility we should check the device's SDK version, and if it's `>= 21`, we'd use `getNextAlarmClock()`, otherwise, fallback to `NEXT_ALARM_FORMATTED` (and support use-cases where it doesn't exist or is improperly-formatted).

Let me know what you think about this. I'd love to see your PR with this improvement.

**Comment by drodda** [comment]
I have made those changes to SystemClock.
There is an issue with AlarmChangedReceiver: it uses the AlarmManager.ACTION_NEXT_ALARM_CLOCK_CHANGED event that was implemented in API 21. This means that it will not automatically detect changes in alarm times. When the app is opened it will check and get the time of the next alarm.
I can not think of an elegant solution other than periodically checking the next alarm.

**Comment by eladnava** [comment]
@drodda Ouch, that's right. I forgot all about that.

I now recall that I once implemented a polling mechanism to periodically check for an updated alarm clock before API level 21 was out.

I think that this may be a bit problematic for our users -- the app might wake them up in the middle of the night with a full-blown sunrise because they changed the alarm clock but haven't opened up Sunriser since then. 

Unfortunately, I'm not sure there is a way to properly support pre-4.4 devices. :(

**Comment by drodda** [comment]
I suspect you may be right. 
I'll reopen if I find a solution.

**Comment by eladnava** [comment]
@drodda Thanks for the the effort!
